const G={owner:"",repo:"",token:"",branch:"main",products:[],config:{},productSha:null,configSha:null};
const $=id=>document.getElementById(id);
function loadCreds(){G.owner=localStorage.getItem("gh_owner")||"";G.repo=localStorage.getItem("gh_repo")||"";G.token=localStorage.getItem("gh_token")||"";$("owner").value=G.owner;$("repo").value=G.repo;$("token").value=G.token}
async function api(path,opts={}){let r=await fetch("https://api.github.com/repos/"+G.owner+"/"+G.repo+"/contents/"+path,{...opts,headers:{Accept:"application/vnd.github+json","Authorization":"Bearer "+G.token,...(opts.headers||{})}});let d=await r.json();if(!r.ok)throw Error(d.message||("GitHub HTTP "+r.status));return d}
async function getFile(path){try{return await api(path)}catch(e){if(e.message.includes("Not Found"))return null;throw e}}
async function readJson(path){let f=await getFile(path);if(!f)return {data:null,sha:null};let txt=decodeURIComponent(escape(atob(f.content.replace(/\n/g,""))));return {data:JSON.parse(txt),sha:f.sha}}
function b64(bytes){let s="";let chunk=0x8000;for(let i=0;i<bytes.length;i+=chunk)s+=String.fromCharCode(...bytes.subarray(i,i+chunk));return btoa(s)}
async function putText(path,text,message,sha){let body={message,content:b64(new TextEncoder().encode(text)),branch:G.branch};if(sha)body.sha=sha;return api(path,{method:"PUT",body:JSON.stringify(body)})}
async function putImage(path,file){let data=await compress(file);let f=await getFile(path);let body={message:"Adicionar foto de produto",content:b64(data),branch:G.branch};if(f)body.sha=f.sha;return api(path,{method:"PUT",body:JSON.stringify(body)})}
async function compress(file){return new Uint8Array(await new Promise((res,rej)=>{let im=new Image(),u=URL.createObjectURL(file);im.onload=()=>{let max=1200,s=Math.min(1,max/Math.max(im.width,im.height)),c=document.createElement("canvas");c.width=Math.round(im.width*s);c.height=Math.round(im.height*s);c.getContext("2d").drawImage(im,0,0,c.width,c.height);c.toBlob(async blob=>{if(!blob)return rej(Error("Falha ao comprimir imagem"));res(await blob.arrayBuffer())},"image/jpeg",.82);URL.revokeObjectURL(u)};im.onerror=rej;im.src=u}))}
async function load(){let p=await readJson("products.json"),c=await readJson("config.json");G.products=p.data||[];G.productSha=p.sha;G.config=c.data||{};G.configSha=c.sha;render();$("storeName").value=G.config.storeName||"";$("subtitle").value=G.config.subtitle||"";$("whatsapp").value=G.config.whatsapp||"";$("status").textContent="Conectado ✓"}
function render(){let el=$("products");el.innerHTML=G.products.map(p=>`<div class="item"><img src="${p.image}"><div><h3>${esc(p.title)}</h3><p>${esc(p.theme||"")}</p></div><div class="actions"><button onclick="edit('${esc(p.id)}')">Editar</button><button class="secondary" onclick="removeProduct('${esc(p.id)}')">Excluir</button></div></div>`).join("")||"<p>Nenhum produto cadastrado.</p>"}
window.edit=id=>{let p=G.products.find(x=>x.id===id);if(!p)return;$("pid").value=p.id;$("oldimage").value=p.image;$("title").value=p.title;$("theme").value=p.theme;$("description").value=p.description||"";scrollTo({top:document.body.scrollHeight/2,behavior:"smooth"})}
window.removeProduct=async id=>{if(!confirm("Excluir este produto do catálogo?"))return;G.products=G.products.filter(p=>p.id!==id);let r=await putText("products.json",JSON.stringify(G.products,null,2),"Excluir produto",G.productSha);G.productSha=r.content.sha;render();alert("Produto excluído.")}
$("connect").onclick=async()=>{G.owner=$("owner").value.trim();G.repo=$("repo").value.trim();G.token=$("token").value.trim();if(!G.owner||!G.repo||!G.token)return alert("Preencha usuário, repositório e token.");localStorage.setItem("gh_owner",G.owner);localStorage.setItem("gh_repo",G.repo);localStorage.setItem("gh_token",G.token);try{await load();alert("Conectado!")}catch(e){alert(e.message)}}
$("product-form").onsubmit=async e=>{e.preventDefault();if(!G.token)return alert("Conecte ao GitHub primeiro.");let id=$("pid").value||crypto.randomUUID();let image=$("oldimage").value;let file=$("photo").files[0];try{if(file){let ext="jpg";let path="assets/products/"+id+"."+ext;await putImage(path,file);image=path}if(!image)return alert("Escolha uma foto.");let item={id,title:$("title").value.trim(),theme:$("theme").value.trim(),image,description:$("description").value.trim()};let idx=G.products.findIndex(x=>x.id===id);if(idx>=0)G.products[idx]=item;else G.products.unshift(item);let r=await putText("products.json",JSON.stringify(G.products,null,2),"Atualizar catálogo",G.productSha);G.productSha=r.content.sha;clearForm();render();alert("Produto publicado!")}
catch(e){alert("Erro: "+e.message)}}
$("clear").onclick=clearForm;function clearForm(){$("product-form").reset();$("pid").value="";$("oldimage").value="";$("preview").style.display="none"}
$("photo").onchange=e=>{let f=e.target.files[0],im=$("preview");if(f){im.src=URL.createObjectURL(f);im.style.display="block"}}
$("saveconfig").onclick=async()=>{try{G.config={...G.config,storeName:$("storeName").value.trim(),subtitle:$("subtitle").value.trim(),whatsapp:$("whatsapp").value.trim()};let r=await putText("config.json",JSON.stringify(G.config,null,2),"Atualizar configurações da loja",G.configSha);G.configSha=r.content.sha;alert("Configurações salvas!")}catch(e){alert(e.message)}}
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
loadCreds();if(G.token)load().catch(()=>{$("status").textContent="Credenciais precisam ser revisadas"});
